### PR TITLE
Fix auto named commands

### LINKED ISSUE #152: Investigate Named Commands in Autonomous not running
Named Commands, if created in the paths themselves, don't appear to be running. Named commands in the _autos_ are running, just not the ones in the _paths._

### PR DESCRIPTION
**Pull request by ACat701**
Closes #152

### CODE REVIEW

File: src/main/java/frc/robot/RobotContainer.java [hunk 1]
```diff
@@ -169,22 +179,25 @@ public void setMegaTag2(boolean setMegaTag2) {
...
             Commands.waitSeconds(1.5),
             TRY_NONE.asProxy().until(() -> !hasCoralTrigger.getAsBoolean())));
 
-    NamedCommands.registerCommand("PrepCoralStation",
-        Commands.print("Prep Coral Station"));
-
     NamedCommands.registerCommand("GetCoralStationPiece",
         Commands.sequence(
             TRY_INTAKING_CORAL_HOPPER.asProxy().until(hasCoralTrigger),
             TRY_PREP_CORAL_L3.asProxy()));
```
Comment (TaylerUva) [inline src/main/java/frc/robot/RobotContainer.java:192]: Should these be removed?

Comment (ACat701) [reply src/main/java/frc/robot/RobotContainer.java:192]: Ooh yeah i missed that one

**Review by TaylerUva — APPROVED** [review]
