### PR TITLE
Fix Climber state softlock (。_。)

### LINKED ISSUE #262: Patch the Climber Softlock
Once we hit either of the climbing buttons, it is impossible in code to go back to the `NONE` state. This means that we softlock ourselves into climbing in the event of a misclick. We need to discuss how we want to determine that it's safe to return to the `NONE` state, but it will probably be similar to what we did with the `CLIMBING` state in our Offbot;
```
case PREP_NONE:
        switch (currentState) {
          case NONE:
          case STORE_FEEDER:
          case PREP_SHUFFLE:
          case PREP_SPEAKER:
          case PREP_WING:
          case PREP_VISION:
          case PREP_SPIKE:
          case PREP_AMP_SHOOTER:
          case PREP_AMP:
          case PREP_NONE:
          case PREP_SUB_BACKWARDS:
            return new PrepTargetState(subElevator, subStateMachine, subShooter, TargetState.PREP_NONE);
          case CLIMBING:
            if (subClimber.isClimberAtPosition(constClimber.BACKWARD_LIMIT)) {
              return new NoneState(subStateMachine, subClimber, subElevator, subIntake, subShooter, subTransfer);
            } else {
              return Commands
                  .print("Attempted to cancel CLIMBING, but the CLIMBER is UP! Please move the climber first :p");
            }
```

### PR DESCRIPTION
**Pull request by Alenguye582**
closes #262

### CODE REVIEW

File: src/main/java/frc/robot/subsystems/Climber.java [hunk 1]
```diff
@@ -41,8 +40,8 @@ public void setClimberMotorVelocity(double velocity) {
     climberMotor2.set(-velocity);
   }
 
-  public Distance getClimberPosition() {
-    return Units.Inches.of(climberMotor.get());
+  public Angle getClimberPosition() {
+    return Units.Rotations.of(climberMotor.getPosition().getValueAsDouble());
```
Comment (TaylerUva) [inline src/main/java/frc/robot/subsystems/Climber.java:44]: You can just do getValue and it will be a unit object

**Review by TaylerUva — CHANGES_REQUESTED** [review]

File: src/main/java/frc/robot/RobotContainer.java [hunk 2]
```diff
@@ -214,8 +214,7 @@ private void configureDriverBindings(SN_XboxController controller) {
         .onFalse(TRY_NONE);
 
     controller.btn_Y
-        .whileTrue(TRY_CLIMBER_RETRACTING)
-        .onFalse(TRY_NONE);
+        .whileTrue(TRY_CLIMBER_RETRACTING);
```
Comment (TaylerUva) [inline src/main/java/frc/robot/RobotContainer.java:218]: I think we need TRY_NONE

**Review by TaylerUva — CHANGES_REQUESTED** [review]

**Review by TaylerUva — APPROVED** [review]
